### ISSUE TITLE
Only works for 1 game

### ISSUE THREAD

**Issue by therealguy9** [salbrandi/bigg#3]
After one game it does not work anymore because it will not select a character in time and instead will go into options or leave the lobby. Any idea how to fix this?

**Comment by salbrandi** [comment]
Ive updated the script and it should work now!

**Comment by therealguy9** [comment]
> 
> 
> Ive updated the script and it should work now!

When you choose "1" for 1 Legend only your legend will not move ingame anymore and only heavy attack, which leads into not getting gold because of not enough activity. Also for some reason my Brawlhalla stops responding after 1-2 games now and I have to restart it, so I cannot let the script run for a long period of time
